// === LEVELS DEFINITIONS ===
// TODOs 7, 11, and 12 will require changes to this section
const LEVELS = [
  {
    name: "Level 1",
    speed: 2,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 950, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1350, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1600, y: groundY },
      { type: "enemy", kind: "bug", x: 1200, y: groundY - 75 },
      { type: "enemy", kind: "bug", x: 1800, y: groundY - 75 },
      { type: "enemy", kind: "bug", x: 1600, y: groundY },
      { type: "powerup", kind: "healthUp", x: 1080, y: groundY - 105 },
      { type: "powerup", kind: "healthUp", x: 1800, y: groundY - 55 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 600,
        y: groundY - 25,
        contactHealthChange: -5,
      },
      { type: "platform", kind: "basicPlatform", x: 900, y: groundY - 55 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1200,
        y: groundY - 85,
        contactHealthChange: -10,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1500,
        y: groundY - 45,
        hp: 0,
      },

      { type: "goal", kind: "flag", x: 2000, y: groundY },
    ],
  },
  {
    name: "Level 2",
    speed: 4,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 800, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1100, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1400, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1900, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1600, y: groundY },
      { type: "enemy", kind: "bug", x: 900, y: groundY - 75 },
      { type: "enemy", kind: "bug", x: 1250, y: groundY - 140 },
      { type: "enemy", kind: "bug", x: 1800, y: groundY - 75 },
      { type: "enemy", kind: "bug", x: 2150, y: groundY - 120 },
      { type: "enemy", kind: "bug", x: 1600, y: groundY },
      { type: "powerup", kind: "healthUp", x: 1080, y: groundY - 105 },
      { type: "powerup", kind: "healthUp", x: 2050, y: groundY - 75 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 600,
        y: groundY - 25,
        contactHealthChange: -5,
      },
      { type: "platform", kind: "basicPlatform", x: 900, y: groundY - 60 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1250,
        y: groundY - 95,
        contactHealthChange: -10,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1650,
        y: groundY - 50,
        hp: 0,
      },

      { type: "goal", kind: "flag", x: 2250, y: groundY },
    ],
  },
  {
    name: "Level 3: Final Run",
    speed: 5,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 700, y: groundY },
      { type: "obstacle", kind: "spikes", x: 950, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1250, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1550, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1850, y: groundY },
      { type: "obstacle", kind: "spikes", x: 2150, y: groundY },
      { type: "obstacle", kind: "spikes", x: 2500, y: groundY },
      { type: "platform", kind: "basicPlatform", x: 650, y: groundY - 25 },
      { type: "platform", kind: "basicPlatform", x: 950, y: groundY - 65 },
      { type: "platform", kind: "basicPlatform", x: 1250, y: groundY - 105 },
      { type: "platform", kind: "basicPlatform", x: 1700, y: groundY - 55 },
      { type: "platform", kind: "basicPlatform", x: 2150, y: groundY - 85 },
      { type: "powerup", kind: "healthUp", x: 1300, y: groundY - 155 },
      { type: "enemy", kind: "bug", x: 800, y: groundY - 75 },
      { type: "enemy", kind: "bug", x: 1100, y: groundY - 160 },
      { type: "enemy", kind: "bug", x: 1450, y: groundY - 75 },
      { type: "enemy", kind: "bug", x: 1750, y: groundY - 210 },
      { type: "enemy", kind: "bug", x: 2050, y: groundY - 75 },
      { type: "enemy", kind: "bug", x: 2400, y: groundY - 150 },
      { type: "goal", kind: "flag", x: 2800, y: groundY },
    ],
  },
];

let currentLevel = LEVELS[0];
let currentLevelIndex = 0;
// === END LEVELS DEFINITIONS ===

// === DEFAULT VALUES FOR EACH "type" AND "kind" OF OBJECT (STUDENT-EDITABLE) ===
const DEFAULT_VALUES = {
  obstacle: {
    spikes: {
      imageUrl: "images/interactable/spikes.png",
      width: 48,
      height: 48,
      hitWidth: 40,
      hitHeight: 44,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: -20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: false,
    },
  },
  enemy: {
    bug: {
      imageUrl: "images/interactable/bug.png",
      width: 75,
      height: 75,
      hitWidth: 75,
      hitHeight: 75,
      speedX: -2,
      speedY: 0,
      minY: 0,
      maxY: groundY - 75,
      contactHealthChange: -30,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 50,
      hp: 3,
      collect: false,
    },
  },
  powerup: {
    healthUp: {
      imageUrl: "images/interactable/healthUp.png",
      width: 32,
      height: 32,
      hitWidth: 32,
      hitHeight: 32,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 32,
      contactHealthChange: +20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  goal: {
    flag: {
      imageUrl: "images/interactable/flag.png",
      width: 100,
      height: 100,
      hitWidth: 100,
      hitHeight: 100,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: 0,
      contactScoreChange: +100,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  platform: {
    basicPlatform: {
      imageUrl: "images/interactable/basicPlatform.png",
      width: 200,
      height: 50,
      hitWidth: 200,
      hitHeight: 50,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 50,
      contactHealthChange: 0,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: Infinity,
      collect: false,
    },
  },
};
// === END DEFAULT VALUES ===
